resolver: lts-19.19
allow-newer: true
packages: 
- .


# Could not load module ‘System.Process’
# It is a member of the hidden package ‘process-1.6.13.2’.
# You can run ‘:set -package process’ to expose it.
# (Note: this unloads all the modules in the current scope.)